In [1]:
import json
out_data = {}

In [2]:
with open("anonymized_and_cleaned_votes.json") as f:
    data = json.load(f)

In [3]:
for player_vote in data:
    tierlist = player_vote["votes"]
    for vote in tierlist:
        voted = vote["choiceUsername"]
        if voted not in out_data:
            out_data[voted] = 0
        out_data[voted] += vote["weight"]

In [4]:
import pandas
pandas.set_option('display.max_rows', None)

df = (
    pandas.DataFrame(out_data.items(), columns=["username", "points"])
    .sort_values("points", ascending=False)
    .reset_index(drop=True)
)

# only the first 10 values
top10 = df.head(10)
top10.index += 1

df.index += 1

# Top 10

In [5]:
top10

           username  points
1              Arge  476.00
2         kiirochii  403.25
3   TheITGovernment  298.50
4            Jabahh  247.75
5          Arancino  231.75
6          Gigi8974  142.00
7           Ryuzaki  120.25
8            Rushio  100.00
9             bgm16   97.00
10  Sakura Nenecchi   89.50

# Full Leaderboard

In [6]:
df

           username  points
1              Arge  476.00
2         kiirochii  403.25
3   TheITGovernment  298.50
4            Jabahh  247.75
5          Arancino  231.75
6          Gigi8974  142.00
7           Ryuzaki  120.25
8            Rushio  100.00
9             bgm16   97.00
10  Sakura Nenecchi   89.50
11  TheECGovernment   72.50
12      Jaki 2Milli   69.25
13             Wido   47.00
14           giulio   30.75
15         Spazza17   29.75
16              mhh   24.50
17          Akahito   21.00
18    shadow modico   18.25
19         -Hideki-   15.00
20             zekk   15.00
21           Ganyu1   14.25
22       SHEKERANDO   14.25
23            dem72   13.75
24            Surpy   12.00
25           Woopak   10.25
26          Markden   10.25
27           Toma 2    9.75
28            Daren    7.75
29           modico    7.50
30        Crazy Hot    7.25
31          DT-sama    7.00
32          zSmoxKe    6.75
33     Amnesia Haze    6.50
34        ReviaKung    6.50
35        Massimo99    6.25
36       Kuromueina    6.25
37             -Tao    5.50
38         -Kazuki-    5.00
39          TWEEKER    5.00
40            Lorax    5.00
41             Nyuh    4.50
42         MirCap72    4.25
43          Kyrichu    4.00
44     Memento Vivi    4.00
45       -Spaghetti    3.00
46         - Menma-    3.00
47          Chiicco    3.00
48         Trivago_    2.75
49    squartatrice_    2.50
50           Mathia    2.50
51         Proioxis    2.50
52        Caparezza    2.25
53           Rommix    2.25
54    Supermattia03    2.00
55            oxeie    2.00
56           Lucyii    2.00
57  Mussolini Pizza    2.00
58     DJ YOSHITAKA    1.75
59         Bluecrow    1.50
60        Panda 4x4    1.50
61   KEKKOKING_0547    1.25
62    dt_gamesplays    1.25
63       LePalleOsu    1.00
64            Kirin    1.00
65      nonsochiama    1.00
66            Rejax    1.00
67            -Doki    1.00
68         Carretto    1.00
69        MinerZeta    1.00
70             Sapo    1.00
71           Cawolo    1.00
72    Bananamagic77    1.00
73             rhyy    0.75
74          -Syncro    0.75
75           Zexsch    0.75
76           Vacsei    0.75
77         Skreddle    0.75
78            _Ecly    0.75

### This is for updating the README.md file. 
You can ignore this if you are not interested

In [7]:
import tabulate
top10_table = tabulate.tabulate(top10, headers='keys', tablefmt='github')
full_table = tabulate.tabulate(df, headers='keys', tablefmt='github')

In [8]:
with open("README.md", "wt") as f:
    print("# Top 10 Italian Players of 2023", file=f)
    print("Forum Post: https://osu.ppy.sh/community/forums/topics/1864118", file=f)
    print("## Top 10 players", file=f)
    print(top10_table, file=f)
    print("## Full Players List", file=f)
    print(full_table, file=f)